Vagrant.configure(2) do |config|

  #vagrant 镜像名,使用 " vagrant box add xxx path " 导入的box可以直接用名字访问。
  config.vm.box = "ubuntu/xenial64"

  #vagrant 名字 比如 vagrant up ljz001
  config.vm.define "ljz002" do |ljz002|
  end
  
  #虚拟机内的主机名
  config.vm.hostname = "ljz002"

  #网络设置
  config.vm.network "private_network", ip: "192.168.32.13"

  #端口映射,guest客户机,host物理机
  #config.vm.network "forwarded_port", guest: 8020, host: 8020


  #虚拟机的相关配置
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "ljz002"
    #vb.gui = true
  end

  #以root用户执行脚本
  config.vm.provision "shell", path: "shell/root.sh"

  #以默认用户执行脚本,privileged为false使用默认用户来执行脚本,否则使用root 用户
  config.vm.provision "shell", path: "shell/default.sh",privileged: false



end
