Vagrant.configure(2) do |config|

  #vagrant 镜像名,使用 " vagrant box add xxx path " 导入的box可以直接用名字访问。
  config.vm.box = "ubuntu/xenial64"

  #vagrant 名字 比如 vagrant up ljz001
  config.vm.define "ljz001" do |ljz001|
  end
  
  #虚拟机内的主机名
  config.vm.hostname = "ljz001"

  #网络设置
  config.vm.network "private_network", ip: "192.168.32.12"

  #端口映射,guest客户机,host物理机
  config.vm.network "forwarded_port", guest: 80, host: 80


  #虚拟机的相关配置
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "ljz001"
    #vb.gui = true
  end

  #shell脚本
  config.vm.provision "shell", path: "shell/bootstrap.sh"



end
